import type { ReadingData } from './api';

type Section = 'Goals' | 'Tasks' | 'Notes';
export default function Reading({ section, data, onAssistant, onComplete, onDelete }: { section: Section; data: ReadingData | null; onAssistant: () => void; onComplete: (id: string) => Promise<void>; onDelete: (kind: 'task' | 'note' | 'quote', id: string) => Promise<void> }) {
  const descriptions = { Goals: 'The milestones you’re reading toward.', Tasks: 'Small steps that make reading a habit.', Notes: 'Thoughts and lines worth keeping.' };
  return <>
    <div className="page-head"><div><span className="eyebrow">YOUR READING JOURNEY</span><h1>{section}<span>.</span></h1><p>{descriptions[section]}</p></div><button className="button-primary" onClick={onAssistant}>Ask Bookwise ↗</button></div>
    {section === 'Goals' && <div className="reading-list">{data?.goals.length ? data.goals.map(goal => <article className="reading-item" key={goal.id}><div className="reading-item-top"><span className="eyebrow">{goal.status}</span><span>{goal.dueDate ? `Due ${goal.dueDate}` : 'No due date'}</span></div><h2>{goal.title}</h2>{goal.description && <p>{goal.description}</p>}<div className="progress-row"><span>Progress</span><strong>{goal.currentProgress} / {goal.target}</strong></div><div className="progress"><i style={{ width: `${Math.min(100, goal.currentProgress / goal.target * 100)}%` }} /></div></article>) : <Empty text="No goals yet. Ask Bookwise to create one for your next book." onAssistant={onAssistant} />}</div>}
    {section === 'Tasks' && <div className="reading-list">{data?.tasks.length ? data.tasks.map(task => <article className="reading-item task-item" key={task.id}><div><span className="eyebrow">{task.status}{task.dueDate ? ` · ${task.dueDate}` : ''}</span><h2>{task.title}</h2>{task.bookTitle && <p>For {task.bookTitle}</p>}{task.description && <p>{task.description}</p>}</div><div className="reading-actions">{task.status === 'PENDING' && <button className="button-secondary" onClick={() => void onComplete(task.id)}>Mark complete</button>}<button className="reading-delete" onClick={() => void onDelete('task', task.id)}>Delete</button></div></article>) : <Empty text="No tasks yet. Ask Bookwise to plan a reading step." onAssistant={onAssistant} />}</div>}
    {section === 'Notes' && <div className="reading-columns"><section><h2>Notes</h2>{data?.notes.length ? data.notes.map(note => <article className="reading-item" key={note.id}><span className="eyebrow">{note.bookTitle}{note.pageNumber ? ` · PAGE ${note.pageNumber}` : ''}</span><p>{note.content}</p>{note.chapter && <small>{note.chapter}</small>}<button className="reading-delete" onClick={() => void onDelete('note', note.id)} aria-label={`Delete note for ${note.bookTitle}`}>Delete</button></article>) : <Empty text="Your book notes will appear here." onAssistant={onAssistant} />}</section><section><h2>Quotes</h2>{data?.quotes.length ? data.quotes.map(quote => <article className="reading-item" key={quote.id}><span className="eyebrow">{quote.bookTitle}{quote.pageNumber ? ` · PAGE ${quote.pageNumber}` : ''}</span><p>“{quote.content}”</p><button className="reading-delete" onClick={() => void onDelete('quote', quote.id)} aria-label={`Delete quote for ${quote.bookTitle}`}>Delete</button></article>) : <Empty text="Saved quotes will appear here." onAssistant={onAssistant} />}</section></div>}
  </>;
}

function Empty({ text, onAssistant }: { text: string; onAssistant: () => void }) {
  return <div className="empty"><span>✦</span><h3>Nothing here yet</h3><p>{text}</p><button className="button-primary" onClick={onAssistant}>Open assistant</button></div>;
}
